"""Add description to user token

Revision ID: 01eeb8ee4a05
Revises: 7a614fb13221
Create Date: 2022-07-31 12:46:44.320984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eeb8ee4a05'
down_revision = '7a614fb13221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_token', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_token', 'description')
    # ### end Alembic commands ###
