"""Add foreign keys from variable to variable sets, avoiding circular SQL dependencies

Revision ID: 031b2c7f8249
Revises: 5c4ea04c4f50
Create Date: 2023-07-26 05:08:33.329589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031b2c7f8249'
down_revision = '5c4ea04c4f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('variable_set_id', sa.Integer(), nullable=True))
    op.add_column('variable', sa.Column('variable_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_variable_variable_version_variable_version_id', 'variable', 'variable_version', ['variable_version_id'], ['id'])
    op.create_foreign_key('fk_variable_variable_set_variable_set_id', 'variable', 'variable_set', ['variable_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_variable_variable_set_variable_set_id', 'variable', type_='foreignkey')
    op.drop_constraint('fk_variable_variable_version_variable_version_id', 'variable', type_='foreignkey')
    op.drop_column('variable', 'variable_version_id')
    op.drop_column('variable', 'variable_set_id')
    # ### end Alembic commands ###
