"""Add team workspace access table

Revision ID: 0805d2e7bece
Revises: 6b6ff14b5fa0
Create Date: 2022-07-31 16:08:56.700872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0805d2e7bece'
down_revision = '6b6ff14b5fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_workspace_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.Enum('READ', 'PLAN', 'WRITE', 'ADMIN', 'CUSTOM', name='teamworkspaceaccesstype'), nullable=True),
    sa.Column('permission_runs', sa.Enum('READ', 'PLAN', 'APPLY', name='teamworkspacerunspermission'), nullable=True),
    sa.Column('permission_variables', sa.Enum('NONE', 'READ', 'WRITE', name='teamworkspacevariablespermission'), nullable=True),
    sa.Column('permission_state_versions', sa.Enum('NONE', 'READ_OUTPUTS', 'READ', 'WRITE', name='teamworkspacestateversionspermissions'), nullable=True),
    sa.Column('permission_sentinel_mocks', sa.Enum('NONE', 'READ', name='teamworkspacesentinelmockspermission'), nullable=True),
    sa.Column('permission_workspace_locking', sa.Boolean(), nullable=True),
    sa.Column('permission_run_tasks', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id', 'team_id', 'workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_workspace_access')
    # ### end Alembic commands ###
