"""Add tables for variables, variable version, variable sets and associations with workspaces and projects

Revision ID: 0864e10e184e
Revises: 18a54e4fe8ad
Create Date: 2023-07-26 04:49:05.529404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0864e10e184e'
down_revision = '18a54e4fe8ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_fk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('variable_set_id', sa.Integer(), nullable=True),
    sa.Column('variable_version_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('TERRAFORM', 'ENV', name='variablecategory'), nullable=False),
    sa.Column('hcl', sa.Boolean(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['api_id_fk'], ['api_id.id'], ),
    sa.ForeignKeyConstraint(['variable_set_id'], ['workspace.id'], ),
    sa.ForeignKeyConstraint(['variable_version_id'], ['variable_version.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_fk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id_fk'], ['api_id.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_set_workspace',
    sa.Column('variable_set_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variable_set_id'], ['variable_set.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('variable_set_id', 'workspace_id')
    )
    op.create_table('variable_set_project',
    sa.Column('variable_set_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['variable_set_id'], ['variable_set.id'], ),
    sa.PrimaryKeyConstraint('variable_set_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable_set_project')
    op.drop_table('variable_set_workspace')
    op.drop_table('variable_set')
    op.drop_table('variable_version')
    op.drop_table('variable')
    # ### end Alembic commands ###
