"""empty message

Revision ID: 10b3cd178079
Revises: 
Create Date: 2022-07-27 22:20:57.922900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b3cd178079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_version',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('speculative', sa.Boolean(), nullable=True),
    sa.Column('auto_queue_runs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_version',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('state_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('configuration_version_id', sa.String(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('plan_only', sa.Boolean(), nullable=True),
    sa.Column('refresh', sa.Boolean(), nullable=True),
    sa.Column('refresh_only', sa.Boolean(), nullable=True),
    sa.Column('is_destroy', sa.Boolean(), nullable=True),
    sa.Column('replace_addrs', sa.String(), nullable=True),
    sa.Column('target_addrs', sa.String(), nullable=True),
    sa.Column('variables', sa.String(), nullable=True),
    sa.Column('terraform_version', sa.String(), nullable=True),
    sa.Column('allow_empty_apply', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('state_version_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan_output', sa.String(), nullable=True),
    sa.Column('log', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['state_version_id'], ['state_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('state_version_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('chnages', sa.String(), nullable=True),
    sa.Column('log', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['state_version_id'], ['state_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply')
    op.drop_table('plan')
    op.drop_table('run')
    op.drop_table('state_version')
    op.drop_table('configuration_version')
    op.drop_table('workspace')
    op.drop_table('organisation')
    # ### end Alembic commands ###
