"""Add ID and API ID foreign key to lifecycle environment

Revision ID: 13c03b88893e
Revises: c27a23b17a83
Create Date: 2023-05-13 17:25:38.822779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13c03b88893e'
down_revision = 'c27a23b17a83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('lifecycle_environment', sa.Column('id', sa.Integer(), nullable=False))
    op.execute("""
    ALTER table lifecycle_environment
        ADD id INT NOT NULL AUTO_INCREMENT,
        DROP FOREIGN KEY lifecycle_environment_ibfk_1,
        DROP FOREIGN KEY lifecycle_environment_ibfk_2,
        DROP PRIMARY KEY,
        ADD PRIMARY KEY (id),
        ADD FOREIGN KEY (`environment_id`) REFERENCES `environment` (`id`),
        ADD FOREIGN KEY (`lifecycle_id`) REFERENCES `lifecycle` (`id`);
    """)
    op.add_column('lifecycle_environment', sa.Column('api_id_fk', sa.Integer(), nullable=True))
    op.alter_column('lifecycle_environment', 'lifecycle_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key('fk_lifecycle_environment_api_id_id', 'lifecycle_environment', 'api_id', ['api_id_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lifecycle_environment_api_id_id', 'lifecycle_environment', type_='foreignkey')
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lifecycle_environment', 'lifecycle_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lifecycle_environment', 'api_id_fk')
    # ### end Alembic commands ###
