"""Add table for saml settings

Revision ID: 18a54e4fe8ad
Revises: a7e334830f17
Create Date: 2023-07-22 06:41:08.328826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a54e4fe8ad'
down_revision = 'a7e334830f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saml_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('debug', sa.String(length=1024), nullable=True),
    sa.Column('old_idp_cert', sa.String(length=1024), nullable=True),
    sa.Column('idp_cert', sa.String(length=1024), nullable=True),
    sa.Column('slo_endpoint_url', sa.String(length=1024), nullable=True),
    sa.Column('sso_endpoint_url', sa.String(length=1024), nullable=True),
    sa.Column('attr_username', sa.String(length=1024), nullable=True),
    sa.Column('attr_groups', sa.String(length=1024), nullable=True),
    sa.Column('attr_site_admin', sa.String(length=1024), nullable=True),
    sa.Column('site_admin_role', sa.String(length=1024), nullable=True),
    sa.Column('sso_api_token_session_timeout', sa.Integer(), nullable=True),
    sa.Column('acs_consumer_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saml_settings')
    # ### end Alembic commands ###
