"""Add fields for s3 state passthrough

Revision ID: 1f555e5ed55f
Revises: 2a2386500260
Create Date: 2022-10-31 08:09:39.622533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f555e5ed55f'
down_revision = '2a2386500260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('state_passthrough_s3_bucket', sa.String(length=128), nullable=True))
    op.add_column('environment', sa.Column('state_passthrough_s3_profile', sa.String(length=128), nullable=True))
    op.add_column('environment', sa.Column('state_passthrough_s3_region', sa.String(length=128), nullable=True))
    op.add_column('project', sa.Column('state_passthrough_s3_key_override', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'state_passthrough_s3_key_override')
    op.drop_column('environment', 'state_passthrough_s3_region')
    op.drop_column('environment', 'state_passthrough_s3_profile')
    op.drop_column('environment', 'state_passthrough_s3_bucket')
    # ### end Alembic commands ###
