"""Add job type column to runqueue

Revision ID: 25ac8c9add40
Revises: cb86637bdbc6
Create Date: 2023-05-01 07:34:54.859309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ac8c9add40'
down_revision = 'cb86637bdbc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_queue', sa.Column('job_type', sa.Enum('WORKER', 'AGENT', name='runqueuetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_queue', 'job_type')
    # ### end Alembic commands ###
