"""Add user type and task execution user run mapping

Revision ID: 279564a0a489
Revises: 0fc7c4dd47a6
Create Date: 2022-09-18 15:49:51.861293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279564a0a489'
down_revision = '0fc7c4dd47a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_execution_user_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('user', sa.Column('user_type', sa.Enum('NORMAL', 'TASK_EXECUTION_USER', name='usertype'), default='NORMAL'))
    c = op.get_bind()
    c.execute("""UPDATE user SET user_type='NORMAL'""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    op.drop_table('task_execution_user_access')
    # ### end Alembic commands ###
