"""Remove lifecycle_id from lifecycle_environment

Revision ID: 35782d9d5895
Revises: 76d3aba866c1
Create Date: 2023-05-14 13:06:49.353578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35782d9d5895'
down_revision = '76d3aba866c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('lifecycle_environment_ibfk_4', 'lifecycle_environment', type_='foreignkey')
    op.drop_column('lifecycle_environment', 'lifecycle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifecycle_environment', sa.Column('lifecycle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('lifecycle_environment_ibfk_2', 'lifecycle_environment', 'lifecycle', ['lifecycle_id'], ['id'])
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
