"""Add constraint to organisation name_id

Revision ID: 445917cb7e83
Revises: 0805d2e7bece
Create Date: 2022-07-31 18:17:07.404268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445917cb7e83'
down_revision = '0805d2e7bece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organisation', ['name_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='unique')
    # ### end Alembic commands ###
