"""Add table for state version output

Revision ID: 455f1d66f6db
Revises: 52699364e8fd
Create Date: 2023-06-30 05:38:01.662251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455f1d66f6db'
down_revision = '52699364e8fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_version_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_fk', sa.Integer(), nullable=True),
    sa.Column('state_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('output_type', sa.String(length=128), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.Column('detailed_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['api_id_fk'], ['api_id.id'], ),
    sa.ForeignKeyConstraint(['state_version_id'], ['state_version.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['blob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_version_output')
    # ### end Alembic commands ###
