"""Add description to environment

Revision ID: 46fb6be21022
Revises: aa199e300fea
Create Date: 2023-05-08 06:25:27.092689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb6be21022'
down_revision = 'aa199e300fea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'description')
    # ### end Alembic commands ###
