"""Remove order column from LifecycleEnvironment

Revision ID: 4a1d3e284ed7
Revises: 35782d9d5895
Create Date: 2023-05-14 17:23:47.523802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a1d3e284ed7'
down_revision = '35782d9d5895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lifecycle_environment', 'lifecycle_environment_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lifecycle_environment', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifecycle_environment', sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lifecycle_environment', 'lifecycle_environment_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
