"""Add resources_processed to state version

Revision ID: 52699364e8fd
Revises: c4ce80ac7594
Create Date: 2023-06-30 05:11:15.405404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52699364e8fd'
down_revision = 'c4ce80ac7594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_version', sa.Column('resources_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state_version', 'resources_processed')
    # ### end Alembic commands ###
