"""Add foreign key for user token to run queue

Revision ID: 5620abf2c8d1
Revises: 0922d468dacd
Create Date: 2023-05-01 13:44:41.494826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5620abf2c8d1'
down_revision = '0922d468dacd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_token', sa.Column('job_id', sa.Integer(), nullable=True))
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'user_token', 'run_queue', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    op.alter_column('user_token', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('user_token', 'job_id')
    # ### end Alembic commands ###
