"""Add agent pool to workspace

Revision ID: 5a50a6d96df7
Revises: b3ce0af0c015
Create Date: 2024-07-29 05:53:50.560501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a50a6d96df7'
down_revision = 'b3ce0af0c015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_pool_environment_association')
    op.drop_table('agent_pool_project_association')
    op.add_column('workspace', sa.Column('agent_pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_workspace_agent_pool_id', 'workspace', 'agent_pool', ['agent_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workspace_agent_pool_id', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'agent_pool_id')
    op.create_table('agent_pool_project_association',
    sa.Column('agent_pool_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], name='agent_pool_project_association_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='agent_pool_project_association_ibfk_2'),
    sa.PrimaryKeyConstraint('agent_pool_id', 'project_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('agent_pool_environment_association',
    sa.Column('agent_pool_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], name='agent_pool_environment_association_ibfk_1'),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], name='agent_pool_environment_association_ibfk_2'),
    sa.PrimaryKeyConstraint('agent_pool_id', 'environment_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
