"""Add GithubAppOauthToken model

Revision ID: 5e4b93710d07
Revises: 3ec6a6ee7249
Create Date: 2023-05-05 20:34:53.654649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4b93710d07'
down_revision = '3ec6a6ee7249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_app_oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_client_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oauth_client_id'], ['oauth_client.id'], name='fk_github_app_oauth_token_oauth_client_oauth_client_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_github_app_oauth_token_user_id_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_app_oauth_token')
    # ### end Alembic commands ###
