"""Add table for assignment of API IDs

Revision ID: 614792b159a0
Revises: 46fb6be21022
Create Date: 2023-05-08 07:32:15.266859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614792b159a0'
down_revision = '46fb6be21022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_suffix', sa.String(length=128), nullable=True),
    sa.Column('object_class', sa.String(length=128), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id_suffix'),
    sa.UniqueConstraint('object_class', 'object_id', name='_object_class_object_id_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_id')
    # ### end Alembic commands ###
