"""Add organisation permissions to team

Revision ID: 6b6ff14b5fa0
Revises: a344666dac49
Create Date: 2022-07-31 15:42:58.588228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6ff14b5fa0'
down_revision = 'a344666dac49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('sso_team_id', sa.String(), nullable=True))
    op.add_column('team', sa.Column('visibility', sa.Enum('ORGANIZATION', 'SECRET', name='teamvisibility'), nullable=True))
    op.add_column('team', sa.Column('manage_policies', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_policy_overrides', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_run_tasks', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_vcs_settings', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_workspaces', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_providers', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('manage_modules', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'manage_modules')
    op.drop_column('team', 'manage_providers')
    op.drop_column('team', 'manage_workspaces')
    op.drop_column('team', 'manage_vcs_settings')
    op.drop_column('team', 'manage_run_tasks')
    op.drop_column('team', 'manage_policy_overrides')
    op.drop_column('team', 'manage_policies')
    op.drop_column('team', 'visibility')
    op.drop_column('team', 'sso_team_id')
    # ### end Alembic commands ###
