"""Add default_execution_mode to organisation

Revision ID: 73ceef3841a1
Revises: 18a54e4fe8ad
Create Date: 2024-07-13 06:51:50.283696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ceef3841a1'
down_revision = '18a54e4fe8ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('default_execution_mode', sa.Enum('REMOTE', 'LOCAL', 'AGENT', name='workspaceexecutionmode'), nullable=False, default='AGENT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'default_execution_mode')
    # ### end Alembic commands ###
