"""Add default agent pool column to organisation

Revision ID: 7d65f74baa78
Revises: 99af3864d169
Create Date: 2024-07-22 06:33:31.828367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d65f74baa78'
down_revision = '99af3864d169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('default_agent_pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_organisation_default_agent_pool_id', 'organisation', 'agent_pool', ['default_agent_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_organisation_default_agent_pool_id', 'organisation', type_='foreignkey')
    op.drop_column('organisation', 'default_agent_pool_id')
    # ### end Alembic commands ###
