"""Add column for custom checksum in tool

Revision ID: 7f5d46e26c9d
Revises: 55527de9c93d
Create Date: 2023-05-12 07:00:08.560223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5d46e26c9d'
down_revision = '55527de9c93d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('sha', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'sha')
    # ### end Alembic commands ###
