"""Add agent and execution mode to plan and apply

Revision ID: 8608a9d79329
Revises: 5a50a6d96df7
Create Date: 2024-07-30 04:52:27.031587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8608a9d79329'
down_revision = '5a50a6d96df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('apply', sa.Column('execution_mode', sa.Enum('REMOTE', 'LOCAL', 'AGENT', name='workspaceexecutionmode'), nullable=True))
    op.create_foreign_key('fk_apply_agent_id', 'apply', 'agent', ['agent_id'], ['id'])
    op.add_column('plan', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('execution_mode', sa.Enum('REMOTE', 'LOCAL', 'AGENT', name='workspaceexecutionmode'), nullable=True))
    op.create_foreign_key('fk_plan_agent_id', 'plan', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_plan_agent_id', 'plan', type_='foreignkey')
    op.drop_column('plan', 'execution_mode')
    op.drop_column('plan', 'agent_id')
    op.drop_constraint('fk_apply_agent_id', 'apply', type_='foreignkey')
    op.drop_column('apply', 'execution_mode')
    op.drop_column('apply', 'agent_id')
    # ### end Alembic commands ###
