"""Add table for state version output

Revision ID: 902945e27303
Revises: 455f1d66f6db
Create Date: 2023-07-02 10:19:49.765984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '902945e27303'
down_revision = '455f1d66f6db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingress_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_fk', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_message', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=128), nullable=False),
    sa.Column('parent_commit_sha', sa.String(length=128), nullable=True),
    sa.Column('on_default_branch', sa.Boolean(), nullable=True),
    sa.Column('pull_request_id', sa.String(length=128), nullable=True),
    sa.Column('pull_request_title', sa.String(length=128), nullable=True),
    sa.Column('pull_request_body', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('sender_username', sa.String(length=128), nullable=True),
    sa.Column('sender_avatar_url', sa.String(length=128), nullable=True),
    sa.Column('authorised_repo_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id_fk'], ['api_id.id'], ),
    sa.ForeignKeyConstraint(['authorised_repo_id'], ['authorised_repo.id'], name='fk_ingress_attributes_authorised_repo_authorised_repo'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], name='fk_ingress_attributes_creator_user_id_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('configuration_version', sa.Column('ingress_attribute_id', sa.Integer(), nullable=True))
    op.create_foreign_key('configuration_version_ingress_attribute_id', 'configuration_version', 'ingress_attribute', ['ingress_attribute_id'], ['id'])
    op.drop_column('configuration_version', 'git_commit_sha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_version', sa.Column('git_commit_sha', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint('configuration_version_ingress_attribute_id', 'configuration_version', type_='foreignkey')
    op.drop_column('configuration_version', 'ingress_attribute_id')
    op.drop_table('ingress_attribute')
    # ### end Alembic commands ###
