"""Add JSON output to state version and make state_version unique

Revision ID: 9309cba5bed5
Revises: c2ecefd99159
Create Date: 2024-08-05 06:39:12.553556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9309cba5bed5'
down_revision = 'c2ecefd99159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_version', sa.Column('json_state_outputs_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_blob_state_version_json_state_outputs', 'state_version', 'blob', ['json_state_outputs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_blob_state_version_json_state_outputs', 'state_version', type_='foreignkey')
    op.drop_column('state_version', 'json_state_outputs_id')
    # ### end Alembic commands ###
