"""Add provider ID to authorised repo model

Revision ID: 94c621ca2c39
Revises: e5a5c75e1ffb
Create Date: 2023-05-06 04:39:22.851713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c621ca2c39'
down_revision = 'e5a5c75e1ffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorised_repo', sa.Column('provider_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorised_repo', 'provider_id')
    # ### end Alembic commands ###
