"""empty message

Revision ID: 9917c4e05b97
Revises: 
Create Date: 2022-07-30 12:26:08.572851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9917c4e05b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('configuration_blob_id', sa.Integer(), nullable=True),
    sa.Column('speculative', sa.Boolean(), nullable=True),
    sa.Column('auto_queue_runs', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FETCHING', 'UPLOADED', 'ARCHIVED', 'ERRORED', name='configurationversionstatus'), nullable=True),
    sa.ForeignKeyConstraint(['configuration_blob_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FETCHING', 'PLAN_QUEUED', 'PLANNING', 'PLANNED', 'COST_ESTIMATING', 'COST_ESTIMATED', 'POLICY_CHECKING', 'POLICY_OVERRIDE', 'POLICY_SOFT_FAILED', 'POLICY_CHECKED', 'CONFIRMED', 'POST_PLAN_RUNNING', 'POST_PLAN_COMPLETED', 'PLANNED_AND_FINISHED', 'APPLY_QUEUED', 'APPLYING', 'APPLIED', 'DISCARDED', 'ERRORED', 'CANCELED', 'FORCE_CANCELLED', name='runstatus'), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('plan_only', sa.Boolean(), nullable=True),
    sa.Column('refresh', sa.Boolean(), nullable=True),
    sa.Column('refresh_only', sa.Boolean(), nullable=True),
    sa.Column('is_destroy', sa.Boolean(), nullable=True),
    sa.Column('replace_addrs', sa.String(), nullable=True),
    sa.Column('target_addrs', sa.String(), nullable=True),
    sa.Column('variables', sa.String(), nullable=True),
    sa.Column('terraform_version', sa.String(), nullable=True),
    sa.Column('allow_empty_apply', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('state_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MANAGE_QUEUED', 'QUEUED', 'RUNNING', 'ERRORED', 'CANCELED', 'FINISHED', 'UNREACHABLE', name='terraformcommandstate'), nullable=True),
    sa.Column('plan_output_id', sa.Integer(), nullable=True),
    sa.Column('plan_output_binary_id', sa.Integer(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['plan_output_binary_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['plan_output_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['state_version_id'], ['state_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('state_version_id', sa.Integer(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MANAGE_QUEUED', 'QUEUED', 'RUNNING', 'ERRORED', 'CANCELED', 'FINISHED', 'UNREACHABLE', name='terraformcommandstate'), nullable=True),
    sa.Column('changes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['state_version_id'], ['state_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply')
    op.drop_table('plan')
    op.drop_table('state_version')
    op.drop_table('run_queue')
    op.drop_table('run')
    op.drop_table('configuration_version')
    op.drop_table('workspace')
    op.drop_table('organisation')
    op.drop_table('blob')
    # ### end Alembic commands ###
