"""Add confirmed flag to run

Revision ID: 9aeeefaf9da5
Revises: 7e7523d13c0d
Create Date: 2022-09-23 17:04:48.317844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aeeefaf9da5'
down_revision = '7e7523d13c0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'confirmed')
    # ### end Alembic commands ###
