"""Add created_by column to run

Revision ID: a40adcec58fb
Revises: d758f66ae94a
Create Date: 2022-08-15 07:35:18.336020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40adcec58fb'
down_revision = 'd758f66ae94a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run') as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('run_created_by_id_user_id', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_column('run', 'created_by_id')
    # ### end Alembic commands ###
