"""Add columns to state version to handle new attributes and upload endpoint

Revision ID: a8e9b3b56d78
Revises: 376a843af267
Create Date: 2024-08-01 06:35:03.953423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8e9b3b56d78'
down_revision = '376a843af267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_version', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('lineage', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('md5', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('serial', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('state_version', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('terraform_version', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('intermediate', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_blob_state_version_state', 'state_version', 'blob', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_blob_state_version_state', 'state_version', type_='foreignkey')
    op.drop_column('state_version', 'intermediate')
    op.drop_column('state_version', 'terraform_version')
    op.drop_column('state_version', 'state_version')
    op.drop_column('state_version', 'serial')
    op.drop_column('state_version', 'md5')
    op.drop_column('state_version', 'lineage')
    op.drop_column('state_version', 'state_id')
    # ### end Alembic commands ###
