"""Add active flag to workspace task to avoid them from being deleted

Revision ID: aaf18e27de97
Revises: 279564a0a489
Create Date: 2022-09-18 16:12:57.240712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf18e27de97'
down_revision = '279564a0a489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_task', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_task', 'active')
    # ### end Alembic commands ###
