"""Add table for OauthToken

Revision ID: afd5cc42b6db
Revises: e44462e3ef30
Create Date: 2023-05-03 05:52:59.839879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afd5cc42b6db'
down_revision = 'e44462e3ef30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('service_provider_user', sa.String(length=128), nullable=False),
    sa.Column('oauth_client_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['oauth_client_id'], ['oauth_client.id'], name='fk_oauth_token_oauth_cient_id_oauth_client_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('oauth_client', 'secret',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('oauth_client', 'oauth_token_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_client', sa.Column('oauth_token_string', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column('oauth_client', 'secret',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_table('oauth_token')
    # ### end Alembic commands ###
