"""Add user column to OauthToken table

Revision ID: b843bb1a95c8
Revises: 3ec6a6ee7249
Create Date: 2023-05-05 19:54:30.911079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b843bb1a95c8'
down_revision = '3ec6a6ee7249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oauth_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_token', type_='foreignkey')
    op.drop_column('oauth_token', 'user_id')
    # ### end Alembic commands ###
