"""Add lifecycle group table, adding between relationships of lifecycle environment and lifecycle

Revision ID: be0b8b8794c9
Revises: 13c03b88893e
Create Date: 2023-05-14 07:06:44.507613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be0b8b8794c9'
down_revision = '13c03b88893e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifecycle_environment_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id_fk', sa.Integer(), nullable=True),
    sa.Column('lifecycle_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('minimum_runs', sa.Integer(), nullable=True),
    sa.Column('minimum_successful_plans', sa.Integer(), nullable=True),
    sa.Column('minimum_successful_applies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id_fk'], ['api_id.id'], name='fk_lifecycle_environment_group_api_id_id'),
    sa.ForeignKeyConstraint(['lifecycle_id'], ['lifecycle.id'], name='fk_lifecycle_environment_group_lifecycle_id_lifecycle_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lifecycle_id', 'order', name='_lifecycle_id_order_uc')
    )
    op.add_column('lifecycle_environment', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('lifecycle_environment', sa.Column('lifecycle_environment_group_id', sa.Integer(), nullable=True))
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint('_lifecycel_id_environment_id_uc', 'lifecycle_environment', ['lifecycle_environment_group_id', 'environment_id'])
    op.drop_constraint('lifecycle_environment_ibfk_2', 'lifecycle_environment', type_='foreignkey')
    op.create_foreign_key('fk_lifecycle_environment_lifecycle_environment_group_id', 'lifecycle_environment', 'lifecycle_environment_group', ['lifecycle_environment_group_id'], ['id'])
    op.drop_column('lifecycle_environment', 'lifecycle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifecycle_environment', sa.Column('lifecycle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint('fk_lifecycle_environment_lifecycle_environment_group_id', 'lifecycle_environment', type_='foreignkey')
    op.create_foreign_key('lifecycle_environment_ibfk_2', 'lifecycle_environment', 'lifecycle', ['lifecycle_id'], ['id'])
    op.drop_constraint('_lifecycel_id_environment_id_uc', 'lifecycle_environment', type_='unique')
    op.alter_column('lifecycle_environment', 'environment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lifecycle_environment', 'lifecycle_environment_group_id')
    op.drop_column('lifecycle_environment', 'id')
    op.drop_table('lifecycle_environment_group')
    # ### end Alembic commands ###
