"""Add job type/agent type column to run queue

Revision ID: c0bad5f1483f
Revises: cb86637bdbc6
Create Date: 2023-05-01 09:04:21.429806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bad5f1483f'
down_revision = 'cb86637bdbc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_queue', sa.Column('agent_type', sa.Enum('WORKER', 'AGENT', name='jobqueueagenttype'), nullable=True))
    op.add_column('run_queue', sa.Column('job_type', sa.Enum('PLAN', 'APPLY', 'POLICY', 'ASSESSMENT', name='jobqueuetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_queue', 'job_type')
    op.drop_column('run_queue', 'agent_type')
    # ### end Alembic commands ###
