"""Add columns to state version to handle new attributes and upload endpoint

Revision ID: c2ecefd99159
Revises: 376a843af267
Create Date: 2024-08-03 05:49:29.376688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2ecefd99159'
down_revision = '376a843af267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename state_json to state column
    op.drop_constraint('state_version_ibfk_3', 'state_version', type_='foreignkey')
    op.alter_column('state_version', 'state_json_id', existing_type=sa.Integer(), nullable=True, new_column_name='state_id')
    op.create_foreign_key('fk_blob_state_version_state', 'state_version', 'blob', ['state_id'], ['id'])

    op.add_column('state_version', sa.Column('json_state_id', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('lineage', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('md5', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('serial', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('state_version', sa.Integer(), nullable=True))
    op.add_column('state_version', sa.Column('terraform_version', sa.String(length=128), nullable=True))
    op.add_column('state_version', sa.Column('intermediate', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_blob_state_version_json_state', 'state_version', 'blob', ['json_state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_blob_state_version_json_state', 'state_version', type_='foreignkey')
    op.drop_constraint('fk_blob_state_version_state', 'state_version', type_='foreignkey')
    op.alter_column('state_version', 'state_id', existing_type=sa.Integer(), nullable=True, new_column_name='state_json_id')
    op.create_foreign_key('state_version_ibfk_3', 'state_version', 'blob', ['state_json_id'], ['id'])
    op.drop_column('state_version', 'intermediate')
    op.drop_column('state_version', 'terraform_version')
    op.drop_column('state_version', 'state_version')
    op.drop_column('state_version', 'serial')
    op.drop_column('state_version', 'md5')
    op.drop_column('state_version', 'lineage')
    op.drop_column('state_version', 'json_state_id')
    op.drop_column('state_version', 'state_id')
    # ### end Alembic commands ###
