"""Add lifecycle attribute to determine whether to allow per-workspace-vcs

Revision ID: c4ce80ac7594
Revises: ba4e612f9537
Create Date: 2023-05-16 06:07:27.501369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ce80ac7594'
down_revision = 'ba4e612f9537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifecycle', sa.Column('allow_per_workspace_vcs', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifecycle', 'allow_per_workspace_vcs')
    # ### end Alembic commands ###
