"""Add missing datetime field from TaskResult

Revision ID: c4e20658ec3a
Revises: aaf18e27de97
Create Date: 2022-09-19 08:15:07.228284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e20658ec3a'
down_revision = 'aaf18e27de97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_result', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_result', 'start_time')
    # ### end Alembic commands ###
