"""Add table for workspace tasks

Revision ID: c6e9a40a39be
Revises: d8e7d7b0b939
Create Date: 2022-08-31 07:56:15.630256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e9a40a39be'
down_revision = 'd8e7d7b0b939'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_task',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('enforcement_level', sa.Enum('ADVISORY', 'MANDATORY', name='workspacetaskenforcementlevel'), nullable=True),
    sa.Column('stage', sa.Enum('PRE_PLAN', 'POST_PLAN', name='workspacetaskstage'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_task')
    # ### end Alembic commands ###
