"""Add enabled flag to workspace and description to meta-workspace

Revision ID: c9abeb4ab0df
Revises: ca2ee390768b
Create Date: 2022-10-12 07:36:13.721865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9abeb4ab0df'
down_revision = 'ca2ee390768b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lifecycle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('meta_workspace', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('meta_workspace', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('workspace', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'enabled')
    op.alter_column('meta_workspace', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('meta_workspace', 'description')
    op.alter_column('lifecycle', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
