"""Add agent pool, agents, agent token and agent pool associations

Revision ID: cb86637bdbc6
Revises: 2a2386500260
Create Date: 2023-04-29 08:46:24.158490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb86637bdbc6'
down_revision = '2a2386500260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('allow_all_workspaces', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'EXITED', 'ERRORED', 'UNKNOWN', 'BUSY', name='agentstatus'), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(), nullable=True),
    sa.Column('agent_pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_pool_environment_association',
    sa.Column('agent_pool_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('agent_pool_id', 'environment_id')
    )
    op.create_table('agent_pool_project_association',
    sa.Column('agent_pool_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('agent_pool_id', 'project_id')
    )
    op.create_table('agent_pool_project_permission',
    sa.Column('agent_pool_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('agent_pool_id', 'project_id')
    )
    op.create_table('agent_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('agent_pool_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['agent_pool_id'], ['agent_pool.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_token')
    op.drop_table('agent_pool_project_permission')
    op.drop_table('agent_pool_project_association')
    op.drop_table('agent_pool_environment_association')
    op.drop_table('agent')
    op.drop_table('agent_pool')
    # ### end Alembic commands ###
