"""Remove file_triggers_enabled flag from workspace/project

Revision ID: d3166f10030f
Revises: fa6ed49416db
Create Date: 2023-07-19 04:53:46.359073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3166f10030f'
down_revision = 'fa6ed49416db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'file_triggers_enabled')
    op.drop_column('workspace', 'file_triggers_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('file_triggers_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('file_triggers_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
