"""Create locked by foriegn key for workspace to User

Revision ID: d67624d8fd3b
Revises: 90149a6955df
Create Date: 2023-05-11 15:40:42.468908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67624d8fd3b'
down_revision = '90149a6955df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('locked_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_workspace_locked_by_user_id_user_id', 'workspace', 'user', ['locked_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workspace_locked_by_user_id_user_id', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'locked_by_user_id')
    # ### end Alembic commands ###
