"""Add plan resource information to plan object

Revision ID: d68c042b816d
Revises: eb90e6532fa6
Create Date: 2023-05-01 15:04:57.441863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68c042b816d'
down_revision = 'eb90e6532fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('has_changes', sa.Boolean(), nullable=True))
    op.add_column('plan', sa.Column('resource_additions', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('resource_changes', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('resource_destructions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'resource_destructions')
    op.drop_column('plan', 'resource_changes')
    op.drop_column('plan', 'resource_additions')
    op.drop_column('plan', 'has_changes')
    # ### end Alembic commands ###
