# Copyright (C) Matt Comben - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
"""Add auto_apply column to workspace

Revision ID: d758f66ae94a
Revises: e1cad9bf1857
Create Date: 2022-08-04 07:47:54.776393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd758f66ae94a'
down_revision = 'e1cad9bf1857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('auto_apply', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'auto_apply')
    # ### end Alembic commands ###
