"""Add AuthorisedRepo model

Revision ID: e5a5c75e1ffb
Revises: 5e4b93710d07
Create Date: 2023-05-06 04:20:43.753936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a5c75e1ffb'
down_revision = '5e4b93710d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorised_repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_changes', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('display_identifier', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('oauth_token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oauth_token_id'], ['oauth_token.id'], name='fk_authorised_repo_oauth_token_id_oauth_token_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorised_repo')
    # ### end Alembic commands ###
