"""Convert state json to blob entity

Revision ID: e83d81428173
Revises: d68c042b816d
Create Date: 2023-05-01 19:02:16.080714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e83d81428173'
down_revision = 'd68c042b816d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_version', sa.Column('state_json_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'state_version', 'blob', ['state_json_id'], ['id'])
    op.drop_column('state_version', 'state_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_version', sa.Column('state_version', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'state_version', type_='foreignkey')
    op.drop_column('state_version', 'state_json_id')
    # ### end Alembic commands ###
