"""Add workspace_task table/modal

Revision ID: f4ebc77f2486
Revises: d8e7d7b0b939
Create Date: 2022-09-17 11:05:32.709744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ebc77f2486'
down_revision = 'd8e7d7b0b939'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('enforcement_level', sa.Enum('ADVISORY', 'MANDATORY', name='workspacetaskenforcementlevel'), nullable=True),
    sa.Column('stage', sa.Enum('PRE_PLAN', 'POST_PLAN', 'POST_APPLY', name='workspacetaskstage'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_task')
    # ### end Alembic commands ###
