"""Add remaining required attributes to organisation

Revision ID: f9b0dc96ba79
Revises: 01eeb8ee4a05
Create Date: 2022-07-31 15:06:44.192371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b0dc96ba79'
down_revision = '01eeb8ee4a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('name_id', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('organisation', sa.Column('session_timeout', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('session_remember', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('collaborator_auth_policy', sa.Enum('PASSWORD', 'TWO_FACTORY_MANDATORY', name='collaboratorauthpolicytype'), nullable=True))
    op.add_column('organisation', sa.Column('cost_estimation_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('configuration_designer_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('operations_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('private_registry_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('sentinel_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('run_tasks_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('state_storage_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('team_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('vcs_integration_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('usage_reporting_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('self_serve_billing_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('audit_logging_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('agents_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('sso_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('fair_run_queuing_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('two_factor_conformant', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('saml_enabled', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('user_limit', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('send_passing_statuses_for_untriggered_speculative_plans', sa.Boolean(), nullable=True))
    op.add_column('organisation', sa.Column('owners_team_saml_role_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'owners_team_saml_role_id')
    op.drop_column('organisation', 'send_passing_statuses_for_untriggered_speculative_plans')
    op.drop_column('organisation', 'user_limit')
    op.drop_column('organisation', 'saml_enabled')
    op.drop_column('organisation', 'two_factor_conformant')
    op.drop_column('organisation', 'fair_run_queuing_enabled')
    op.drop_column('organisation', 'sso_enabled')
    op.drop_column('organisation', 'agents_enabled')
    op.drop_column('organisation', 'audit_logging_enabled')
    op.drop_column('organisation', 'self_serve_billing_enabled')
    op.drop_column('organisation', 'usage_reporting_enabled')
    op.drop_column('organisation', 'vcs_integration_enabled')
    op.drop_column('organisation', 'team_enabled')
    op.drop_column('organisation', 'state_storage_enabled')
    op.drop_column('organisation', 'run_tasks_enabled')
    op.drop_column('organisation', 'sentinel_enabled')
    op.drop_column('organisation', 'private_registry_enabled')
    op.drop_column('organisation', 'operations_enabled')
    op.drop_column('organisation', 'configuration_designer_enabled')
    op.drop_column('organisation', 'cost_estimation_enabled')
    op.drop_column('organisation', 'collaborator_auth_policy')
    op.drop_column('organisation', 'session_remember')
    op.drop_column('organisation', 'session_timeout')
    op.drop_column('organisation', 'created_at')
    op.drop_column('organisation', 'email')
    op.drop_column('organisation', 'name_id')
    # ### end Alembic commands ###
