"""Add created date to ingress attribute

Revision ID: fa6ed49416db
Revises: 370bc07a467e
Create Date: 2023-07-15 06:43:01.503355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6ed49416db'
down_revision = '370bc07a467e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingress_attribute', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingress_attribute', 'created_at')
    # ### end Alembic commands ###
