"""Add http URL and webhook ID to authorised repo

Revision ID: fcebb3b28fb6
Revises: eda573028296
Create Date: 2023-05-06 05:22:12.563866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcebb3b28fb6'
down_revision = 'eda573028296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorised_repo', sa.Column('http_url', sa.String(length=128), nullable=True))
    op.add_column('authorised_repo', sa.Column('webhook_id', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorised_repo', 'webhook_id')
    op.drop_column('authorised_repo', 'http_url')
    # ### end Alembic commands ###
