image: python:3.10

.limit_release_and_non_pushes:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\):.*/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - when: never

e2e-tests:
  stage: test
  extends: .limit_release_and_non_pushes
  image: docker:cli
  tags: [amd64]
  script:
    - sh ./tests/e2e/run_tests.sh


release:
  stage: deploy
  image: semantic-release:latest
  cache:
    paths:
      - node_modules/
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GIT_STRATEGY: clone
  script:
    - semantic-release
  rules:
    - if: '$CI_COMMIT_REF_NAME != "main"'
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /chore\(release\)/'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - when: never

stages:
 - build
 - test
 - deploy
